### ISSUE TITLE
In add stocks list Brand name, Model Name, Unit shows as read only

### ISSUE THREAD

**Issue by coreoceantesting** [govind663/IT_Assets_Management#12]
Brand, Model, and Unit fields are shown as read-only bcz this data is shown as per category and product name
![image](https://github.com/govind663/IT_Assets_Management/assets/145965034/42144676-8527-45e4-b353-7d4cbd2a5698)

**Comment by govind663** [comment]
![Screenshot (8)](https://github.com/govind663/IT_Assets_Management/assets/65995420/3776d746-b244-41eb-bfb5-4076636d6fab)

**Comment by coreoceantesting** [comment]
Ok Done
