### ISSUE TITLE
User form not editable

### ISSUE THREAD

**Issue by coreoceantesting** [govind663/IT_Assets_Management#17]
In editing any field and submitting the error is shown
![image](https://github.com/govind663/IT_Assets_Management/assets/145965034/2bfb5183-789f-4b2d-ac8e-1cb960b10501)
Click On submit-->Issue-->
![image](https://github.com/govind663/IT_Assets_Management/assets/145965034/9f6e46db-3b0e-4f04-a797-e0a841e91d07)

**Comment by govind663** [comment]
![Screenshot (10)](https://github.com/govind663/IT_Assets_Management/assets/65995420/8c5a96b5-0b49-4d76-8e5d-a8d11b1d3a6f)
![Screenshot (12)](https://github.com/govind663/IT_Assets_Management/assets/65995420/7f2f6d07-2161-4c5e-b26d-7fb1ff784cd9)
