### ISSUE TITLE
Error is showing while creating New User

### ISSUE THREAD

**Issue by coreoceantesting** [govind663/IT_Assets_Management#8]
![image](https://github.com/govind663/IT_Assets_Management/assets/145965034/26d28d6d-f894-4407-95c9-2bd961e00ace)
SQL error is showing

**Comment by govind663** [comment]
![Screenshot (4)](https://github.com/govind663/IT_Assets_Management/assets/65995420/801bfdc3-1fa1-4d7e-9ded-ef6ff23beb79)

**Comment by coreoceantesting** [comment]
Done
